#!/bin/bash

# Note - you will need to be root to run this!

set -e

if [[ ! -d "/mnt/ramdrive" ]]; then
    mkdir /mnt/ramdrive
fi

mount -t tmpfs -o size=1G tmpfs /mnt/ramdrive

dataDir=/mnt/ramdrive/rtslam.data
capDir=${dataDir}/captures
mkdir -p ${capDir}/runDump

if [[ -d /DevProj/AR/rt-slam.data/captures/runLive ]]; then
    cfgDir=/DevProj/AR/rt-slam.data/captures/runLive
else
    cfgDir=/Developer/Projects/rtslam/jafar/captures/runLive
fi

cp -r ${cfgDir} ${capDir}
ln -s runLive/setup.cfg ${capDir}/setup.cfg
ln -s runLive/estimation.cfg ${capDir}/estimation.cfg

chown -R paulm ${dataDir}
chgrp -R dev ${dataDir}