#!/bin/bash
THIS_FILE=$(python -c "import os; print os.path.normcase(os.path.normpath(os.path.realpath(os.path.abspath('''$0'''))))")
THIS_DIR=$(dirname "$THIS_FILE")

NUM_REPEATS=$1
if [[ -z $NUM_REPEATS ]]; then
    NUM_REPEATS=1
fi

if [[ -z $DEMO_SLAM ]]; then
    DEMO_SLAM=demo_slam
fi

if [[ -z "$JAFAR_DIR" ]]; then
    testPath=$(which $DEMO_SLAM)
    testPath=$(python -c "import os; print os.path.normcase(os.path.normpath(os.path.realpath(os.path.abspath('''$testPath'''))))")
    # try to find JAFAR_DIR by checking parent dirs
    relCam=/modules/gdhe/data/camera.tcl
    lastPath=""
    while [[ -n "$testPath" && "$lastPath" != "$testPath" ]]; do
        if [[ -f "${testPath}/modules/gdhe/data/camera.tcl" ]]; then
            export JAFAR_DIR="$testPath"
            break
        fi
        lastPath="$testPath"
        testPath=$(dirname "$lastPath")
    done
fi

echo "JAFAR_DIR:" $JAFAR_DIR

if [[ -z "$SETUP_CFG" ]]; then
    SETUP_CFG="@/setup.cfg"
fi

if [[ -z "$EST_CFG" ]]; then
    EST_CFG="@/estimation.cfg"
fi

cmd=("$DEMO_SLAM" --replay=1  --robot=1 --pause=0 --dump=0 --log=1 --render-all=0 --disp-2d=1 --disp-3d=1 --data-path="$THIS_DIR" --config-setup="$SETUP_CFG" --config-estimation="$EST_CFG" --rand-seed=0 --freq=100)

pyCmd='import os
import sys
pathTemplate = os.path.join(sys.argv[1], "rtslam.replay%02d.log")
num = 1
while(True):
    path = pathTemplate % num
    if not os.path.isfile(path):
        break
    num += 1
print path'

for execNum in $(seq $NUM_REPEATS)
do
    echo "${cmd[@]}"
    eval "${cmd[@]}"

    replayLog=$(python -c "$pyCmd" "$THIS_DIR")
    echo "copying ${THIS_DIR}/rtslam.log to $replayLog"
    cp "${THIS_DIR}/rtslam.log" "$replayLog"
done
