#!/bin/bash

DISP=""
DISP="--disp-2d"
#DISP="--disp-2d --disp-3d"
#DISP="--disp-2d --disp-osg"
#DISP="--disp-3d"
#DISP="--disp-osg"
#DISP="--disp-2d --disp-3d --disp-osg"

# malloc error after frame 265, 282
#RSEED=1333191916

# malloc error after frame 1486
#RSEED=1333211841

# out of range index error at frame 195
RSEED=1334429335

FREQ=100

# Random
#RSEED=0

REPLAY=0
REPLAY_DUMP=0
PAUSE=1
DUMP=0
LOG=1
RENDERALL=0
ROBOT=0
VIEWS=1

echo $REPLAY

MODEL=
#MODEL="@/cow.osg"
MODEL="/DevProj/AR/rt-slam/jafar/src/modules/rtslam/data/models/MTi.osg"

if [[ "$(uname -s)" == "Linux" ]]
then
    export RTSLAMBASE=/DevProj/AR/rt-slam
    ARCH_DIR=x86_64-linux-gnu
else
    export RTSLAMBASE=/Developer/Projects/rtslam
    ARCH_DIR=i386-darwin-gnu
fi

export JAFAR_BASE=$RTSLAMBASE/jafar
export JAFAR_DIR=$JAFAR_BASE/src
thisDir=$(basename $(pwd))
if [[ "$thisDir" == "debug" || "$thisDir" == "release" ]];
then
    export JAFAR_BUILD=$JAFAR_BASE/build/$thisDir
else
    export JAFAR_BUILD=$JAFAR_BASE/build/release
fi

export OSG_WINDOW="0 0 640 480"

if (( $REPLAY_DUMP ))
then
    REPLAY=1
fi

if (( $REPLAY ))
then
    if [[ "${DISP}" == "" ]]
    then
        PAUSE=0
    fi
    DATAPATH=$JAFAR_BASE/captures/testSeq
    if (( ! $REPLAY_DUMP ))
    then
        ROBOT=0
    fi
else
    DATAPATH=$JAFAR_BASE/captures
    PAUSE=0
fi

if (( $DUMP || $REPLAY_DUMP ))
then
    DATAPATH=$JAFAR_BASE/captures/runDump
fi

if (( $DUMP && ! $REPLAY_DUMP ))
then
    SETUP_CFG=@/../setup.cfg
    EST_CFG=@/../estimation.cfg
else
    SETUP_CFG=@/setup.cfg
    EST_CFG=@/estimation.cfg
fi

# for luma branch
cmd="$JAFAR_BUILD/modules/rtslam/demo_suite/$ARCH_DIR/demo_slam --replay=$REPLAY $DISP --robot=$ROBOT --pause=$PAUSE --dump=$DUMP --log=$LOG --render-all=$RENDERALL --data-path=$DATAPATH --config-setup=${SETUP_CFG} --config-estimation=${EST_CFG} --rand-seed=$RSEED --freq=$FREQ --num-views=$VIEWS --model=$MODEL"
# for patch branch
#cmd="$JAFAR_BUILD/modules/rtslam/demo_suite/$ARCH_DIR/demo_slam --replay=$REPLAY $DISP --robot=$ROBOT --pause=$PAUSE --dump=$DUMP --log=$LOG --render-all=$RENDERALL --data-path=$DATAPATH --config-setup=${SETUP_CFG} --config-estimation=${EST_CFG} --rand-seed=$RSEED --freq=$FREQ"
echo "$cmd"
eval "$cmd"
